language: node_js
node_js:
  - '0.10'
before_install:
  - currentfolder=${PWD##*/}
  - if [ "$currentfolder" != 'generator-flat' ]; then cd .. && eval "mv $currentfolder generator-flat" && cd generator-flat; fi

